- name: declaring variables in ansible playbook
  hosts: local 
  connection: local 
  vars:
   COURSE: devops
   TRAINER: sivakumar
   DURATION: 10HR
  
  tasks:
  - name: print the course details 
    ansible.builtin.debug:
     msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}" 
  
  tasks:
  - name: print the course details again
    ansible.builtin.debug:
     msg: "course name is {{ COURSE }}, trainer name is {{ DURAION }}"
  
  
  
