- name: declaring variables in ansible playbook
  hosts: local 
  connection: local 
  vars:   # declaring the varables 
   COURSE: devops
   TRAINER=ansible
   DURATION=10hr
  
  tasks:
  - name: print the course details 
    ansible.builtin.debug:
     msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}" 
  
  - name: print the course details again
    ansible.builtin.debug:
     msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}"
  
  
  
