- name: declaring task variables 
  hosts: local 
  connection: local 
  vars: 
   COURSE: devops
   TRAINER: sivakumar
   DURATION: 10hr 

   tasks:
   - name: print the course details
    #  vars:
    #   COURSE: aws
    #   TRAINER: prasanth
    #   DURATION: 14hr
     ansible.builtin.debug:
      msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}"

   - name: print the course details
     ansible.builtin.debug:
      msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}"

     