- name: calling variables to a pirticular node
  hosts: node1
  tasks:
  - name: print from node1
    ansible.builtin.debug:
     msg: "course name is {{ COURSE }}, trainer name is {{ TRAINER }}, course duration is {{ DURATION }}"