- name: installing packages
  hosts: local
  connection: local
  become: yes
  tasks:
   - name: installing packages using loop 
     ansible.builtin.package:
      name: " {{ item }} "
      state: present 
     loop:
      - nginx
      - httpd
      - java