- name: functions # we have pre defined functions in yaml we can use them 
  hosts: local
  connection: local
  vars:
   PERSON:
   - sriram 
   - kiran
   - venkat 
   - rathod
  tasks: 
  
   - name: default function 
     ansible.builtin.debug:
      msg: "{{ PERSON | default('rathod') }}"  # default module 
   
   - name: split function 
     ansible.builtin.debug:
      msg: "{{ PERSON | split(',') }}"


     
