- name: functions # we have pre defined functions in yaml we can use them 
  hosts: local
  connection: local
  vars:
   PERSON: "rathod,venkat,sriram,kiran"
  tasks: 
  
   - name: default function 
     ansible.builtin.debug:
      msg: "{{ PERSON | default('rathod') }}"  # default module 
   
   - name: split function 
     ansible.builtin.debug:
      msg: "{{ PERSON | split('/') }}"


     
