- name: functions # we have pre defined functions in yaml we can use them 
  hosts: local
  connection: local
  vars:
   PERSON: "sriram,kiran,nandha,venkat"
   
  tasks: 
  
   - name: default function 
     ansible.builtin.debug:
      msg: "{{ PERSON | default('rathod') }}"  # default module 
   
   - name: split function 
     ansible.builtin.debug:
      msg: "{{ PERSON | split(',') }}" # split function will n ot work for list objects only work for string 
   
   - name: covert map to list 
     vars: 
      COURSE:
       name: devops
       duration: 20hr 
       trainer: nandha
     ansible.builtin.debug:
      msg: "{{ COURSE | dict2items }}"

   - name: convert list to map # 
     vars:
      COURSE:
       - { key: 'name', value: 'devops'}
       - { key: 'trainer', value: 'nandha'}
       - { key: 'duration', value: '10hr' } 
     ansible.builtin.debug:
      msg : "{{ COURSE | items2dist }}"


     
